# Generated by Django 4.1 on 2022-08-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="가계부 제목")),
                ("balance", models.IntegerField(default=0, verbose_name="가계부 시작 금액")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일자")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일자")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제여부")),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_book",
                        to="users.user",
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountBookRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="날짜")),
                ("memo", models.CharField(max_length=100, verbose_name="메모내용")),
                ("amount", models.IntegerField(verbose_name="금액")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일자")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일자")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제여부")),
                (
                    "account_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_book_record",
                        to="account_books.accountbook",
                        verbose_name="가계부",
                    ),
                ),
            ],
        ),
    ]
